// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARgvIaUA4b_GT8JT66PPEnJou8GjcRtvI',
    appId: '1:672507171917:web:58556eeb85874ff9eeb804',
    messagingSenderId: '672507171917',
    projectId: 'nursdb-c1628',
    authDomain: 'nursdb-c1628.firebaseapp.com',
    storageBucket: 'nursdb-c1628.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1SVtKcOEioeckeuR2qfi-1LtCNkMqJdw',
    appId: '1:672507171917:android:1d0f17eb1315742eeeb804',
    messagingSenderId: '672507171917',
    projectId: 'nursdb-c1628',
    storageBucket: 'nursdb-c1628.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD71uWHzp3zGd6jEY9YKSY9kDRyiaGrxMA',
    appId: '1:672507171917:ios:b416293ab420b9eceeb804',
    messagingSenderId: '672507171917',
    projectId: 'nursdb-c1628',
    storageBucket: 'nursdb-c1628.firebasestorage.app',
    iosBundleId: 'com.example.tacabAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD71uWHzp3zGd6jEY9YKSY9kDRyiaGrxMA',
    appId: '1:672507171917:ios:b416293ab420b9eceeb804',
    messagingSenderId: '672507171917',
    projectId: 'nursdb-c1628',
    storageBucket: 'nursdb-c1628.firebasestorage.app',
    iosBundleId: 'com.example.tacabAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARgvIaUA4b_GT8JT66PPEnJou8GjcRtvI',
    appId: '1:672507171917:web:4e6cfe8bc657c932eeb804',
    messagingSenderId: '672507171917',
    projectId: 'nursdb-c1628',
    authDomain: 'nursdb-c1628.firebaseapp.com',
    storageBucket: 'nursdb-c1628.firebasestorage.app',
  );
}
