// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD40L0kSdR5HQ1rV9_SpEzo6zovqu3j07E',
    appId: '1:612599198984:web:0243b13d0cfde9a15068bd',
    messagingSenderId: '612599198984',
    projectId: 'tacab-ai',
    authDomain: 'tacab-ai.firebaseapp.com',
    storageBucket: 'tacab-ai.firebasestorage.app',
    measurementId: 'G-NC3GG9W9Z4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZKzRddJRJNUZ0pkunnQ9pRAvA7cR2ZZc',
    appId: '1:612599198984:android:167e2b86fbb899f05068bd',
    messagingSenderId: '612599198984',
    projectId: 'tacab-ai',
    storageBucket: 'tacab-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzhae-06rsuT9av8KDIKalWmLW2QWPYeU',
    appId: '1:612599198984:ios:93a8e907af8fe4155068bd',
    messagingSenderId: '612599198984',
    projectId: 'tacab-ai',
    storageBucket: 'tacab-ai.firebasestorage.app',
    iosBundleId: 'com.example.tacabAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzhae-06rsuT9av8KDIKalWmLW2QWPYeU',
    appId: '1:612599198984:ios:93a8e907af8fe4155068bd',
    messagingSenderId: '612599198984',
    projectId: 'tacab-ai',
    storageBucket: 'tacab-ai.firebasestorage.app',
    iosBundleId: 'com.example.tacabAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD40L0kSdR5HQ1rV9_SpEzo6zovqu3j07E',
    appId: '1:612599198984:web:c99668047cd686ee5068bd',
    messagingSenderId: '612599198984',
    projectId: 'tacab-ai',
    authDomain: 'tacab-ai.firebaseapp.com',
    storageBucket: 'tacab-ai.firebasestorage.app',
    measurementId: 'G-FLSR4KXZ3V',
  );
}
